### ISSUE TITLE
invalid integer ''

### ISSUE THREAD

**Issue by matthew-groth** [fisherman/get#4]
When I use the command `get` with no arguments I get the output:
```
test returned eval errors:
        invalid integer ''
```

Which occurs on the line 73:
```
    if test "$count" -le 0
```

I tried debugging but I don't really know how to fix this because I don't understand what `$count`  does.

**Comment by lepisma** [comment]
Count looks like the *number* from `-s, --silent[=number]`. Changing line 4 to `set -l count 0` should fix it.

**Comment by phatblat** [comment]
@lepisma I tried that and got errors when the `--silent` flag is present. I just created #6 before noticing you made #5 😆

**Comment by Markcial** [comment]
Hi, just let you know that you can use the `-a` or `-o` flags to combine conditions, it is not necessary to use the `and|or` builtins.

For example, just to check that a variable is a numerical and that it has a bigger value than 0:

     set foo 1;test -z "$foo" -a $foo -gt 0

Both of you came out with great solutions, but at the end, test already works like expected. It is issuing a message to the stderr that he was expecting an integer. So it is not necessary to do prior comparisons, simply silencing that output would be enough.

     test "" -gt 0
     > test returned eval errors:
     > invalid integer ''
     test "" -gt 0 ^ /dev/null # no output

I will apply the pipe redirect fix, because the test operation would get more complex chaining conditions.
